### ISSUE TITLE
Can't Edit Length of an XM

### ISSUE THREAD

**Issue by 730730** [kode54/foo_dumb#7]
Not sure if this is the appropriate place to post this, but it's the only thing I could come up with. Anyways, I want to edit the length of an XM so I can convert it into an extended OGG or something of the sort, but there's no option to do this, as there is with other plugins. Maybe it's just a limitation of the format, in which case, is there a way to manually edit it? The only thing I managed to achieve was getting a file 00:25:55 long which just looped the first section.

**Comment by kode54** [comment]
You can only control how many times it loops, using the looping setting. If you want it to loop more than the song already loops, you'll need to look into editing it in a tracker, such as OpenMPT.

**Comment by 730730** [comment]
Ah thanks, did it with OpenMPT :)
