### ISSUE TITLE
Unable to play certain .mod file to the end

### ISSUE THREAD

**Issue by raspi** [kode54/foo_dumb#8]
When using "Use playptmod or modplay" DUMB can't go pass 0:19 of this song. Disabling "Use playptmod or modplay" fixes issue.

Version 1.0.157

Upstream issue?

ftp://modland.ziphoid.com/pub/modules/Protracker/Nightlight/dirt.mod
http://janeway.exotica.org.uk/release.php?id=32999#downloads
https://www.dropbox.com/s/6ahm17y6oyxtgln/DIRT.MOD?dl=0

**Comment by kode54** [comment]
Bug in a speed 0 handler in playptmod, which I have just corrected. Sneaky composer!
